name: GCP Deploy
on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cloud Functions Deploy
        uses: google-github-actions/deploy-cloud-functions@v0.1.2
        with:
          credentials: ${{ secrets.GCP_SA_KEY }}
          name: PageSpeed_vuanem
          env_vars: "API_KEY=${{ secrets.API_KEY }},\
            BUCKET=${{ secrets.BUCKET }},\
            PATH_TO_FILE=${{ secrets.PATH_TO_FILE }}"
          entry_point: main
          runtime: python38
          service_account_email: ${{ secrets.GCP_SA }}
